import { normalizeIconName } from '@/utils/iconName'

/** Íconos (Font Awesome Pro solid) que se ofrecen al elegir el ícono de una categoría. */
export const CATEGORY_ICON_OPTIONS: ReadonlyArray<{ value: string; label: string }> = [
  { value: 'wine-bottle', label: 'Jarrón / botella' },
  { value: 'flower-tulip', label: 'Flor' },
  { value: 'flower', label: 'Flores' },
  { value: 'flower-daffodil', label: 'Narciso' },
  { value: 'leaf', label: 'Hoja' },
  { value: 'leaf-maple', label: 'Hoja de maple' },
  { value: 'tree', label: 'Árbol' },
  { value: 'fence', label: 'Cerca' },
  { value: 'shovel', label: 'Jardín' },
  { value: 'house-tree', label: 'Exterior' },
  { value: 'plate-wheat', label: 'Bandejas' },
  { value: 'layer-group', label: 'Capas' },
  { value: 'cheese-swiss', label: 'Tablas de queso' },
  { value: 'cheese', label: 'Quesos' },
  { value: 'utensils', label: 'Cubiertos' },
  { value: 'plate-utensils', label: 'Platos' },
  { value: 'kitchen-set', label: 'Cocina' },
  { value: 'pot-food', label: 'Ollas' },
  { value: 'bowl-food', label: 'Bowls' },
  { value: 'mug-hot', label: 'Tazas' },
  { value: 'jar', label: 'Frascos' },
  { value: 'mortar-pestle', label: 'Mortero' },
  { value: 'faucet-drip', label: 'Grifos' },
  { value: 'faucet', label: 'Grifo' },
  { value: 'fire', label: 'Velas / fuego' },
  { value: 'candle-holder', label: 'Candelero' },
  { value: 'lamp', label: 'Lámpara' },
  { value: 'lamp-floor', label: 'Lámpara de piso' },
  { value: 'lightbulb', label: 'Iluminación' },
  { value: 'chess-queen', label: 'Esculturas' },
  { value: 'chess-bishop', label: 'Figura' },
  { value: 'monument', label: 'Monumento' },
  { value: 'gem', label: 'Joya' },
  { value: 'frame', label: 'Cuadros' },
  { value: 'image', label: 'Imagen' },
  { value: 'palette', label: 'Arte' },
  { value: 'house', label: 'Hogar' },
  { value: 'house-chimney', label: 'Casitas' },
  { value: 'couch', label: 'Sala' },
  { value: 'bed', label: 'Dormitorio' },
  { value: 'rug', label: 'Alfombras' },
  { value: 'spa', label: 'Aromas / spa' },
  { value: 'dove', label: 'Aves' },
  { value: 'feather', label: 'Plumas' },
  { value: 'bell', label: 'Campana' },
  { value: 'wreath', label: 'Corona' },
  { value: 'gift', label: 'Regalo' },
  { value: 'gifts', label: 'Regalos' },
  { value: 'heart', label: 'Corazón' },
  { value: 'star', label: 'Estrella' },
  { value: 'crown', label: 'Corona real' },
  { value: 'sparkles', label: 'Destacados' },
  { value: 'sun', label: 'Verano' },
  { value: 'pumpkin', label: 'Otoño' },
  { value: 'tree-christmas', label: 'Navidad' },
  { value: 'candy-cane', label: 'Navideño' },
  { value: 'snowflake', label: 'Invierno' },
  { value: 'box-open', label: 'Varios' },
  { value: 'tag', label: 'Etiqueta' },
]

/** Clase completa para <q-icon :name>, p. ej. 'leaf' → 'fa-solid fa-leaf'. */
export function categoryIconClass(icon: string | undefined): string {
  return normalizeIconName(icon) ?? 'fa-solid fa-tag'
}
